mod Error {
    const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';
    const INVALID_DECIMALS: felt252 = 'INVALID_DECIMALS';
    const INVALID_NAME: felt252 = 'INVALID_NAME';
    const INVALID_SYMBOL: felt252 = 'INVALID_SYMBOL';
}
